services:
  - type: web
    name: mango-portfolio
    env: node
    plan: free
    buildCommand: npx vite build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.10