services:
  - type: web
    name: mango-portfolio
    env: node
    plan: free
    buildCommand: npm install --force && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.10