services:
  - type: web
    name: mango-portfolio
    env: node
    plan: free
    buildCommand: npm install && npx vite build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 4173
