services:
  - type: web
    name: mango-portfolio
    env: node
    plan: free
    buildCommand: npm install --production=false && npm run build && npm install vite
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.10