services:
  - type: web
    name: Mango-portfolio
    env: static
    staticPublishPath: public
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
